version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    depends_on:
      - checker
    environment:
      - HTTP_ADDR=:8080
      - GRPC_SERVICE_URL=checker:50051
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - tg-network
    volumes:
      - ./:/app

  checker:
    build:
      context: .
      dockerfile: cmd/checker/Dockerfile
    depends_on:
      - db
    environment:
      - SERVER_ADDR=:50051
      - TELEGRAM_TIMEOUT=5s
      - DATABASE_URL=postgres://postgres:pass@db:5432/telegram?sslmode=disable
    ports:
      - "50051:50051"
    restart: unless-stopped
    networks:
      - tg-network
    volumes:
      - ./:/app

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=telegram
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - tg-network

volumes:
  postgres-data:

networks:
  tg-network:
    driver: bridge
